export const Howwework = [

  {
    id: "01",
    image: "/backgrounds/img1.png",
    underlinetitile: "D i s c u  ",
    simpletitle: "s s i o n & a n a n l y s i s .",
    heading: "Objective",
    objectivekeys1: [
      "To understand the requirements of clients.",
      "To Finalize the budget Plan.",

    ],
    heading2: "DELIVERABLE",
    deliverablekeys: [
      "Finalized Project Cost Sheet.",
      "Project Timeline.",
      "Initial infographic prototype.",
    ],
    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },
  {
    id: "02",
    image: "/backgrounds/img2.png",
    underlinetitile: "P l a n n",
    simpletitle: " i n g & d e s i g n",
    heading: "Objective",
    objectivekeys1: [
      "To set deliverables",
      "To extract the meaningful information from clients requirements",
      "To forecast the possible coming challenges",
      "To set a sprint timeline for each phase of the project",
    ],
    heading2: "DELIVERABLE",
    deliverablekeys: [
      "Delivering initial infographics prototype to the client",
      "Different Modules deliverable timelines",
    ],
    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },

  {
    id: "03",
    image: "/backgrounds/img3.png",
    underlinetitile: "S o f t w ",
    simpletitle: "a r e d e s i g n",
    heading: "Objective",
    objectivekeys1: ["To finalize the themes", "To design all the screens"],
    heading2: "DELIVERABLE",
    deliverablekeys: ["Front end", "Skeletal framework"],

    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],

    heading4: "tools used",
    toolskeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },
  {
    image: "/backgrounds/img4.png",
    underlinetitile: "S o f t w ",
    simpletitle: "a r e d e v e l o p m e n t",
    heading: "Objective",
    objectivekeys1: [
      "To Split different modules to sprints",
      "To develop backend accordingly to the clients requirements",
      "To connect Front-End to Back-End",
    ],
    heading2: "DELIVERABLE",
    deliverablekeys: ["Alpha version delivery", "Detailed documentation"],
    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],

    heading4: "tools used",
    toolskeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },
  {
    image: "/backgrounds/img5.png",
    underlinetitile: "Q u a l i t ",
    simpletitle: "y a s s u r a n c e",
    heading: "Objective",
    objectivekeys1: [
      "QA & QC team to ensure the client-centric quality",
      "Beta version delivery",
    ],
    heading2: "DELIVERABLE",
    deliverablekeys: ["Beta Version", "Operating Manual"],
    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],

    heading4: "tools used",
    toolskeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },
  {
    image: "/backgrounds/img6.png",
    underlinetitile: "M a i n t ",
    simpletitle: "a i n a n c e",
    heading: "Objective",
    objectivekeys1: [
      "To incorporate the reviews of product manager and clients in every sprints",
      "To provide the Release Candidates (RC 1, RC 2 and RC 3)",
    ],
    heading2: "DELIVERABLE",
    deliverablekeys: ["Release Candidates", "Operating Manual"],
    heading3: "TEAM MEMBER INVOLVED",
    memberkeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],

    heading4: "tools used",
    toolskeys: [
      "CTO",
      "Project Manager",
      "Development Lead",
      "UI & UX Lead",
      "Client",
      "Business Analyst",
    ],
  },
];
